config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'schedules#index'
  # resources :users, only: [:index, :edit, :update, :show]
  resources :users, only: [:index, :new, :edit, :update, :show] do 
    resource :ownpage, only: [:new, :create, :show, :edit, :update]
  end
  resources :schedules, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ownpage.rb
class Ownpage < ApplicationRecord
  # belongs_to :user
  has_many :schedules, through: :schedule_ownpages
  has_many :schedule_ownpages
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :users, through: :user_schedules
  has_many :user_schedules
  has_many :ownpages, through: :schedule_ownpages
  has_many :schedule_ownpages
end

app/models/schedule_ownpage.rb
class ScheduleOwnpage < ApplicationRecord
  belongs_to :ownpage
  belongs_to :schedule
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :schedules, through: :user_schedules
  has_many :user_schedules
  # belongs_to :ownpage

  validates :name, presence: true, uniqueness: true
end

app/models/user_schedule.rb
class UserSchedule < ApplicationRecord
  belongs_to :user
  belongs_to :schedule
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/ownpages_controller.rb
class OwnpagesController < ApplicationController
  before_action :set_user, only: [:new, :show, :edit, :upload]

  def new
    # binding.pry
    @ownpage = Ownpage.new
    # @ownpage = @user.ownpage.new
  end

  def create
    @ownpage = Ownpage.new(ownpage_params)
  end
  
  def show
    # @ownpage = @user.ownpage.find(params[:id])
    # @user = User.find(params[:user_id])
    # @name = @user.name
  end

  def edit
    # @ownpage = Ownpage.new
    @ownpage = Ownpage.find(params[:user_id])
  end

  def update
    # binding.pry
    # @ownpage = Ownpage.new(ownpage_params)
    # @ownpage = Ownpage.find(params[:user_id])
    # if @ownpage.update(ownpage_params)
    #   redirect_to root_path, notice: "ok"
    # else
    #   redirect_to new_user_ownpage_path, notice: "no"
    # end
  end

  private

    def set_user
      @user = User.find(params[:user_id])
      @name = @user.name
    end

    def ownpage_params
      params.require(:ownpage).permit(:image, :content).merge(user_id: current_user.id)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def index
    @user = Schedule.new
    @user = User.all
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_user

  def index
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.new
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    user = User.find(params[:id])
    @name = user.name
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  # def set_user
  #   @user = User.find(params[:user_id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PresenceChart
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/ownpages/_chartShort.html.haml
%table{border: "2", height: "160", width: "700"}
  %tr{align: "center"}

    %th 9:00
    %th 10:00
    %th 11:00
    %th 12:00
    %th 13:00
    %th 14:00
    %th 15:00

  %tr{align: "center"}
    %td{ class:"target"}
      = link_to "#", class:"chartBtnS1" do
        □
    %td
      = link_to "#", class:"chartBtnS2" do
        □
    %td
      = link_to "#", class:"chartBtnS3" do
        □
    %td
      = link_to "#", class:"chartBtnS4" do
        □
    %td
      = link_to "#", class:"chartBtnS5" do
        □
    %td
      = link_to "#", class:"chartBtnS6" do
        □
    %td
      = link_to "#", class:"chartBtnS7" do
        □

app/views/ownpages/_show_schedule.html.haml
.BaseShow
  .BaseShow__schedule
    .BaseShow__schedule__title
      今日の予定
    .BaseShow__schedule__digest
      = render "chartShort"
    .BaseShow__schedule__btnArea
      .BaseShow__schedule__btnArea__previousDay
        = link_to "#", class: "BaseShow__schedule__btnArea__previousDay__btn" do
          前日
      .BaseShow__schedule__btnArea__detail
        = link_to root_path, class: "BaseShow__schedule__btnArea__detail__btn" do
          詳細
      .BaseShow__schedule__btnArea__nextDay
        = link_to "#", class: "BaseShow__schedule__btnArea__nextDay__btn" do
          翌日

app/views/ownpages/_show_user.html.haml
.BaseShow
  .BaseShow__user
    .BaseShow__user__name
      = @user.name
      -# = link_to new_user_ownpage_path, class:"BaseShow__user__name__edit" do
      = link_to edit_user_ownpage_path, class:"BaseShow__user__name__edit" do
        編集
    .BaseShow__user__photo
      = form_with url:"#", class: "BaseShow__user__photo__step" do |k|
        = k.file_field :photo, class: "BaseShow__user__photo__step__edit"
    .BaseShow__user__message
      -# .BaseShow__user__message__form
      -#   .BaseShow__user__message__form__space
      -#     = @ownpage.content
      = form_with url:"#", class: "BaseShow__user__message__form" do |i|
        = i.text_area :message, placeholder: "message", class:"BaseShow__user__message__form__space"
    .BaseShow__user__comment
      コメントスペース

app/views/ownpages/edit.html.haml
.BaseEdit
  = form_with(url: "/users/:user_id/ownpage", model: @ownpage, method: :put, local: true) do |i|
    .BaseEdit__user
      .BaseEdit__name
        = @user.name
        = i.submit "更新", class: "BaseEdit__send"
        = link_to user_ownpage_path, class:"BaseEdit__back" do
          戻る
      .BaseEdit__photo
        .BaseEdit__step
          = i.file_field :photo, class: "BaseEdit__edit"
      .BaseEdit__message
        .BaseEdit__space
          = i.text_area :content, placeholder: "message", class:"BaseEdit__textArea"
      .BaseEdit__comment
        コメントスペース
      

app/views/ownpages/new.html.haml
.BaseEdit
  = form_with(url: "/users/:user_id/ownpage", model: @ownpage, method: :post, local: true) do |i|
    .BaseEdit__user
      .BaseEdit__name
        = @user.name
        = i.submit "更新", method: :post, class: "BaseEdit__send"
      .BaseEdit__photo
        .BaseEdit__step
          = i.file_field :photo, class: "BaseEdit__edit"
      .BaseEdit__message
        .BaseEdit__space
          = i.text_area :content, placeholder: "message", class:"BaseEdit__textArea"
      .BaseEdit__comment
        コメントスペース
      

app/views/ownpages/show.html.haml
.BaseShow
  = render "show_user"
  = render "show_schedule"

app/views/schedules/_chart.html.haml
%table{border: "2", height: "160", width: "1350"}
  %tr{align: "center"}
    %th 5:00
    %th 6:00
    %th 7:00
    %th 8:00
    %th 9:00
    %th 10:00
    %th 11:00
    %th 12:00
    %th 13:00
    %th 14:00
    %th 15:00
    %th 16:00
    %th 17:00
    %th 18:00
    %th 19:00
    %th 20:00
    %th 21:00
    %th 22:00
    %th 23:00
    %th 0:00
    %th 1:00
    %th 2:00
    %th 3:00
    %th 4:00
  %tr{align: "center"}
    %td{ class:"target"}
      -# = link_to "#", class:"chartBtnA1" do
      .chartBtnA1
        □
    %td
      -# = link_to "#", class:"chartBtnA2" do
      .chartBtnA2
        □
    %td
      -# = link_to "#", class:"chartBtnA3" do
      .chartBtnA3
        □
    %td
      -# = link_to "#", class:"chartBtnA4" do
      .chartBtnA4
        □
    %td
      -# = link_to "#", class:"chartBtnA5" do
      .chartBtnA5
        □
    %td
      -# = link_to "#", class:"chartBtnA6" do
      .chartBtnA6
        □
    %td
      -# = link_to "#", class:"chartBtnA7" do
      .chartBtnA7
        □
    %td
      -# = link_to "#", class:"chartBtnA8" do
      .chartBtnA8
        □
    %td
      -# = link_to "#", class:"chartBtnA9" do
      .chartBtnA9
        □
    %td
      -# = link_to "#", class:"chartBtnA10" do
      .chartBtnA10
        □
    %td
      -# = link_to "#", class:"chartBtnA11" do
      .chartBtnA11
        □
    %td
      -# = link_to "#", class:"chartBtnA12" do
      .chartBtnA12
        □
    %td
      -# = link_to "#", class:"chartBtnA13" do
      .chartBtnA13
        □
    %td
      -# = link_to "#", class:"chartBtnA14" do
      .chartBtnA14
        □
    %td
      -# = link_to "#", class:"chartBtnA15" do
      .chartBtnA15
        □
    %td
      -# = link_to "#", class:"chartBtnA16" do
      .chartBtnA16
        □
    %td
      -# = link_to "#", class:"chartBtnA17" do
      .chartBtnA17
        □
    %td
      -# = link_to "#", class:"chartBtnA18" do
      .chartBtnA18
        □
    %td
      -# = link_to "#", class:"chartBtnA19" do
      .chartBtnA19
        □
    %td
      -# = link_to "#", class:"chartBtnA20" do
      .chartBtnA20
        □
    %td
      -# = link_to "#", class:"chartBtnA21" do
      .chartBtnA21
        □
    %td
      -# = link_to "#", class:"chartBtnA22" do
      .chartBtnA22
        □
    %td
      -# = link_to "#", class:"chartBtnA23" do
      .chartBtnA23
        □
    %td
      -# = link_to "#", class:"chartBtnA24" do
      .chartBtnA24
        □
  %tr{align: "center"}
    %td{ class:"target"}
      -# = link_to "#", class:"chartBtnB1" do
      .chartBtnB1
        □
    %td
      -# = link_to "#", class:"chartBtnB2" do
      .chartBtnB2
        □
    %td
      -# = link_to "#", class:"chartBtnB3" do
      .chartBtnB3
        □
    %td
      -# = link_to "#", class:"chartBtnB4" do
      .chartBtnB4
        □
    %td
      -# = link_to "#", class:"chartBtnB5" do
      .chartBtnB5
        □
    %td
      -# = link_to "#", class:"chartBtnB6" do
      .chartBtnB6
        □
    %td
      -# = link_to "#", class:"chartBtnB7" do
      .chartBtnB7
        □
    %td
      -# = link_to "#", class:"chartBtnB8" do
      .chartBtnB8
        □
    %td
      -# = link_to "#", class:"chartBtnB9" do
      .chartBtnB9
        □
    %td
      -# = link_to "#", class:"chartBtnB10" do
      .chartBtnB10
        □
    %td
      -# = link_to "#", class:"chartBtnB11" do
      .chartBtnB11
        □
    %td
      -# = link_to "#", class:"chartBtnB12" do
      .chartBtnB12
        □
    %td
      -# = link_to "#", class:"chartBtnB13" do
      .chartBtnB13
        □
    %td
      -# = link_to "#", class:"chartBtnB14" do
      .chartBtnB14
        □
    %td
      -# = link_to "#", class:"chartBtnB15" do
      .chartBtnB15
        □
    %td
      -# = link_to "#", class:"chartBtnB16" do
      .chartBtnB16
        □
    %td
      -# = link_to "#", class:"chartBtnB17" do
      .chartBtnB17
        □
    %td
      -# = link_to "#", class:"chartBtnB18" do
      .chartBtnB18
        □
    %td
      -# = link_to "#", class:"chartBtnB19" do
      .chartBtnB19
        □
    %td
      -# = link_to "#", class:"chartBtnB20" do
      .chartBtnB20
        □
    %td
      -# = link_to "#", class:"chartBtnB21" do
      .chartBtnB21
        □
    %td
      -# = link_to "#", class:"chartBtnB22" do
      .chartBtnB22
        □
    %td
      -# = link_to "#", class:"chartBtnB23" do
      .chartBtnB23
        □
    %td
      -# = link_to "#", class:"chartBtnB24" do
      .chartBtnB24
        □
  %tr{align: "center"}
    %td
      -# = link_to "#", class:"chartBtnC1" do
      .chartBtnC1
        □
    %td
      -# = link_to "#", class:"chartBtnC2" do
      .chartBtnC2
        □
    %td
      -# = link_to "#", class:"chartBtnC3" do
      .chartBtnC3
        □
    %td
      -# = link_to "#", class:"chartBtnC4" do
      .chartBtnC4
        □
    %td
      -# = link_to "#", class:"chartBtnC5" do
      .chartBtnC5
        □
    %td
      -# = link_to "#", class:"chartBtnC6" do
      .chartBtnC6
        □
    %td
      -# = link_to "#", class:"chartBtnC7" do
      .chartBtnC7
        □
    %td
      -# = link_to "#", class:"chartBtnC8" do
      .chartBtnC8
        □
    %td
      -# = link_to "#", class:"chartBtnC9" do
      .chartBtnC9
        □
    %td
      -# = link_to "#", class:"chartBtnC10" do
      .chartBtnC10
        □
    %td
      -# = link_to "#", class:"chartBtnC11" do
      .chartBtnC11
        □
    %td
      -# = link_to "#", class:"chartBtnC12" do
      .chartBtnC12
        □
    %td
      -# = link_to "#", class:"chartBtnC13" do
      .chartBtnC13
        □
    %td
      -# = link_to "#", class:"chartBtnC14" do
      .chartBtnC14
        □
    %td
      -# = link_to "#", class:"chartBtnC15" do
      .chartBtnC15
        □
    %td
      -# = link_to "#", class:"chartBtnC16" do
      .chartBtnC16
        □
    %td
      -# = link_to "#", class:"chartBtnC17" do
      .chartBtnC17
        □
    %td
      -# = link_to "#", class:"chartBtnC18" do
      .chartBtnC18
        □
    %td
      -# = link_to "#", class:"chartBtnC19" do
      .chartBtnC19
        □
    %td
      -# = link_to "#", class:"chartBtnC20" do
      .chartBtnC20
        □
    %td
      -# = link_to "#", class:"chartBtnC21" do
      .chartBtnC21
        □
    %td
      -# = link_to "#", class:"chartBtnC22" do
      .chartBtnC22
        □
    %td
      -# = link_to "#", class:"chartBtnC23" do
      .chartBtnC23
        □
    %td
      -# = link_to "#", class:"chartBtnC24" do
      .chartBtnC24
        □
  %tr{align: "center"}
    %td
      -# = link_to "#", class:"chartBtnD1" do
      .chartBtnD1
        □
    %td
      -# = link_to "#", class:"chartBtnD2" do
      .chartBtnD2
        □
    %td
      -# = link_to "#", class:"chartBtnD3" do
      .chartBtnD3
        □
    %td
      -# = link_to "#", class:"chartBtnD4" do
      .chartBtnD4
        □
    %td
      -# = link_to "#", class:"chartBtnD5" do
      .chartBtnD5
        □
    %td
      -# = link_to "#", class:"chartBtnD6" do
      .chartBtnD6
        □
    %td
      -# = link_to "#", class:"chartBtnD7" do
      .chartBtnD7
        □
    %td
      -# = link_to "#", class:"chartBtnD8" do
      .chartBtnD8
        □
    %td
      -# = link_to "#", class:"chartBtnD9" do
      .chartBtnD9
        □
    %td
      -# = link_to "#", class:"chartBtnD10" do
      .chartBtnD10
        □
    %td
      -# = link_to "#", class:"chartBtnD11" do
      .chartBtnD11
        □
    %td
      -# = link_to "#", class:"chartBtnD12" do
      .chartBtnD12
        □
    %td
      -# = link_to "#", class:"chartBtnD13" do
      .chartBtnD13
        □
    %td
      -# = link_to "#", class:"chartBtnD14" do
      .chartBtnD14
        □
    %td
      -# = link_to "#", class:"chartBtnD15" do
      .chartBtnD15
        □
    %td
      -# = link_to "#", class:"chartBtnD16" do
      .chartBtnD16
        □
    %td
      -# = link_to "#", class:"chartBtnD17" do
      .chartBtnD17
        □
    %td
      -# = link_to "#", class:"chartBtnD18" do
      .chartBtnD18
        □
    %td
      -# = link_to "#", class:"chartBtnD19" do
      .chartBtnD19
        □
    %td
      -# = link_to "#", class:"chartBtnD20" do
      .chartBtnD20
        □
    %td
      -# = link_to "#", class:"chartBtnD21" do
      .chartBtnD21
        □
    %td
      -# = link_to "#", class:"chartBtnD22" do
      .chartBtnD22
        □
    %td
      -# = link_to "#", class:"chartBtnD23" do
      .chartBtnD23
        □
    %td
      -# = link_to "#", class:"chartBtnD24" do
      .chartBtnD24
        □

app/views/schedules/_index_html.html.haml
.Top
  .Top__upper
    = link_to "#", class: "Top__upper__loginBtn" do
      ログイン
  .Top__middle
    .Top__middle__date
      = render "today"
    .Top__middle__title
      タイトル
  .Top__bottom
    = link_to "#", class: "Top__bottom__previousDayBtn" do
      前日
    = link_to "#", class: "Top__bottom__nextDayBtn" do
      翌日

app/views/schedules/_index_schedule.html.haml
.Bottom
  .Bottom__user
    name
    - @user.each do |i|
      .Bottom__user__nameBox
        -# = link_to user_path(i.id), class: "Bottom__user__nameBox__name" do
        -#   = i.name
        = link_to user_ownpage_path(i.id), class: "Bottom__user__nameBox__name" do
          = i.name
  .Bottom__schedule
    .Bottom__schedule__body
      = render "chart"

app/views/schedules/_index_upper.html.haml
.Top
  .Top__upper
    = link_to edit_user_path(current_user), class: "Top__upper__loginBtn" do
      出入口
  .Top__middle
    .Top__middle__date
      %input#today{:type => "date"}/
    .Top__middle__title
      タイトル
  .Top__bottom
    = link_to "#", class: "Top__bottom__previousDayBtn" do
      前日
    = link_to "#", class: "Top__bottom__nextDayBtn" do
      翌日

app/views/schedules/_new_login.html.haml
.BaseNew
  .BaseNew__login
    = form_with url:"#", class: "BaseNew__login__area" do |i|
      .BaseNew__login__area__title
        ログイン
      .BaseNew__login__area__name
        name : 
        = i.text_field :name, placeholder: "name"
      .BaseNew__login__area__pass
        password : 
        = i.text_field :password, placeholder: "password"
      .BaseNew__login__area__loginBtn
        = i.submit "ログイン"

app/views/schedules/_new_newcomer.html.haml
.BaseNew
  .BaseNew__newEntry
    .BaseNew__newEntry__title
      新規登録
    = form_with url:"#", class: "BaseNew__newEntry__area__form" do |i|
      .BaseNew__newEntry__form__name
        name : 
        = i.text_field :name, placeholder: "name"
      .BaseNew__newEntry__form__email
        email :
        = i.text_field :email, placeholder: "email"
      .BaseNew__newEntry__form__pass
        password : 
        = i.text_field :password, placeholder: "password"
      .BaseNew__newEntry__form__again
        password again : 
        = i.text_field :password_again, placeholder: "again"
    = form_with url:"#", class: "BaseNew__newEntry__entry" do |k|
      = k.submit "登録", class: "BaseNew__newEntry__entry__btn"

app/views/schedules/_show_schedule.html.haml
.BaseShow
  .BaseShow__schedule
    .BaseShow__schedule__title
      今日の予定
    .BaseShow__schedule__digest
      ダイジェスト
    .BaseShow__schedule__btnArea
      .BaseShow__schedule__btnArea__previousDay
        = link_to "#", class: "BaseShow__schedule__btnArea__previousDay__btn" do
          前日
      .BaseShow__schedule__btnArea__detail
        = link_to "#", class: "BaseShow__schedule__btnArea__detail__btn" do
          詳細
      .BaseShow__schedule__btnArea__nextDay
        = link_to "#", class: "BaseShow__schedule__btnArea__nextDay__btn" do
          翌日

app/views/schedules/_show_user.html.haml
.BaseShow
  .BaseShow__user
    .BaseShow__user__name
      ユーザーネーム
      = link_to "#", class:"BaseShow__user__name__edit" do
        編集
    .BaseShow__user__photo
      = form_with url:"#", class: "BaseShow__user__photo__step" do |k|
        = k.file_field :photo, class: "BaseShow__user__photo__step__edit"
    .BaseShow__user__message
      = form_with url:"#", class: "BaseShow__user__message__form" do |i|
        = i.text_area :message, placeholder: "message", class:"BaseShow__user__message__form__space"
    .BaseShow__user__comment
      コメントスペース

app/views/schedules/_today.html.haml
:javascript 
  var today = new Date()
  var year = today.getFullYear();
  var month = today.getMonth()+1;
  var week = today.getDay();
  var day = today.getDate();

  var week_ja= new
  Array("日", "月", "火", "水", "木", "金", "土");

  document.write(month + "/" + day + "(" + week_ja[week] + ")");

app/views/schedules/index.html.haml
.Base
  = render "index_upper"
  = render "index_schedule"

app/views/schedules/new.html.haml
.BaseNew
  = render "new_newcomer"
  = render "new_login"

app/views/users/_show_schedule.html.haml
.BaseShow
  .BaseShow__schedule
    .BaseShow__schedule__title
      今日の予定
    .BaseShow__schedule__digest
      = render "ownpages/chartShort"
    .BaseShow__schedule__btnArea
      .BaseShow__schedule__btnArea__previousDay
        = link_to "#", class: "BaseShow__schedule__btnArea__previousDay__btn" do
          前日
      .BaseShow__schedule__btnArea__detail
        = link_to root_path, class: "BaseShow__schedule__btnArea__detail__btn" do
          詳細
      .BaseShow__schedule__btnArea__nextDay
        = link_to "#", class: "BaseShow__schedule__btnArea__nextDay__btn" do
          翌日

app/views/users/_show_user.html.haml
.BaseShow
  .BaseShow__user
    .BaseShow__user__name
      = @name
      = link_to "#", class:"BaseShow__user__name__edit" do
        編集
    .BaseShow__user__photo
      = form_with url:"#", class: "BaseShow__user__photo__step" do |k|
        = k.file_field :photo, class: "BaseShow__user__photo__step__edit"
    .BaseShow__user__message
      = form_with url:"#", class: "BaseShow__user__message__form" do |i|
        = i.text_area :message, placeholder: "message", class:"BaseShow__user__message__form__space"
    .BaseShow__user__comment
      コメントスペース

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", root_path, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/users/show.html.haml
.BaseShow
  = render "show_user"
  = render "show_schedule"